### ISSUE TITLE
How do you use this package?

### ISSUE THREAD

**Issue by vasilevich** [primus/primus-msgpack#82]
Hello!
Thank you for making this package,  but I noticed that your README lacks any examples.

I am currently using featherjs through primus on the client/server side.
can you please give an example how to use your package "primus-msgpack"  with primus, or with it?

thank you!

**Comment by lpinca** [comment]
Install the package and use the `parser` option as documented here https://github.com/primus/primus#parsers. The value of the option must be `'msgpack'`.

```js
var primus = new Primus(server, { parser: 'msgpack' });
```
